### ISSUE TITLE
Haxe 4.1.0: __js__ is deprecated, use js.Syntax.code instead

### ISSUE THREAD

**Issue by CedX** [haxetink/tink_chunk#15]
When using this package with Haxe 4.1.0 and compiling to Node.js target, I get this deprecation warning:

`tink_chunk/0,3,1/src/tink/chunk/nodejs/BufferChunk.hx:49: characters 17-23 : Warning : __js__ is deprecated, use js.Syntax.code instead`

This is not blocking, but annoying to activate the `no-deprecation-warnings` compiler flag.

**Comment by kevinresol** [comment]
PR would be very appreciated.
